spring.application.name=coshift-backend

# --- IMPORT DU FICHIER .ENV ---
# Permet à Spring Boot de lire ton fichier .env à la racine
spring.config.import=optional:file:.env

# --- BASE DE DONNÉES (WAMP / MySQL) ---
# Connexion locale standard de WAMP sur le port 3306
spring.datasource.url=jdbc:mysql://localhost:3306/coshift_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- FLYWAY pour les migrations ---
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Dialecte MySQL pour que Hibernate génère les bonnes requêtes
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- SÉCURITÉ (Temporaire pour le dév) ---
spring.security.user.name=admin
spring.security.user.password=admin123

# --- JWT ---
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=${JWT_EXPIRATION}

# --- API EXTERNES ---
api.gnews.key=${GNEWS_API_KEY}
api.newsdata.key=${NEWSDATA_API_KEY}

# Active le pool de threads pour les tâches planifiées
spring.task.scheduling.pool.size=2

# Configuration Google OAuth2
api.google.client-id=415112384949-i0jihhuatgp8hrnuvptqujenhmmn0kb1.apps.googleusercontent.com