spring.application.name=coshift-backend

# --- BASE DE DONNÉES (WAMP) ---
spring.datasource.url=jdbc:mysql://localhost:3306/coshift_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- SÉCURITÉ (Temporaire pour le dév) ---
# On définit un user par défaut pour ne pas être bloqué par Spring Security au début
spring.security.user.name=admin
spring.security.user.password=admin123


# --- SÉCURITÉ ---
# On récupère les valeurs du .env
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=${JWT_EXPIRATION}
